#!/bin/bash

#curl http://localhost:3001/addPeer -H "Content-type:application/json" --data '{"peer" : "ws://localhost:6001"}' 
curl -H "Content-type:application/json" --data '{"peer" : "ws://localhost:6001"}' http://localhost:3001/addPeer
